apiVersion: v1
kind: Service
metadata:
  labels:
    metrics: enabled
  name: autoscaling-metrics
spec:
  selector:
    run: spc-autoscaler
  ports:
  - name: metrics
    port: 8085
    protocol: TCP
    targetPort: metrics
  type: ClusterIP
